### ISSUE TITLE
Bootstraping nodes

### ISSUE THREAD

**Issue by nahuelange** [isaaczafuta/pydht#1]
Hi, thanks for you work.
Does your library support bootstraping nodes from a "tracker"?
I saw in example that you connect directly to a known and already existing node, but what if we don't know the node?

**Comment by isaaczafuta** [comment]
This DHT implementation is not (currently) compatible with the bittorrent DHT protocol.

In all DHTs, a new node must have knowledge of at least one other node that bootstraps it onto the network.  BT clients are often hardcoded with a node to help them bootstrap, common ones are router.bittorrent.org, router.utorrent.com, and dht.transmissionbt.org.  Likewise, torrent metainfo files can contain a 'nodes' key with known DHT nodes as specified by [1](www.bittorrent.org/beps/bep_0005.html).

I'd recommend looking at Entangled or a similar client.
